### ISSUE TITLE
Downward control too fast

### ISSUE THREAD

**Issue by ecobsama** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-28#21]
Are we suppose to tap it instead of full auto? Because its way too fast like the recoil got reversed 😂

**Comment by Kava4** [comment]
--====== Vertical Sensitivity Multiplier Settings =========--

-- !Important You still have to do all the other recommended settings in the folder.
-- With this SensSetting you can use your own Vertical Sensitivity Multiplier to fit it with your own mouse speed.
-- To understand the logic check the the ready settings below. 
-- HOWEVER You can use any General Sensitivity Setting or any DPI to fit your mouse speed. It will not effect the recoil pattern.
-- We recommend not to change any setting if it's not really necessary. It's only a optional feature.

--######################################################################################################--
--##########################           Ready Sensitivity Setting             ###########################--
--######################################################################################################--
--##############  For Vertical Sensitivity Multiplier 0.50 Set the SensSetting to 2    #################--
--##############  For Vertical Sensitivity Multiplier 0.75 Set the SensSetting to 1.33 #################--
--##############  For Vertical Sensitivity Multiplier 1 Set the SensSetting to 1       #################--
--##############  For Vertical Sensitivity Multiplier 1.5 Set the SensSetting to 0.675 #################--
--##############  For Vertical Sensitivity Multiplier 2 Set the SensSetting to 0.50    #################--
--######################################################################################################--
--######################################################################################################--


local SensSetting = 1  --> !! Change it for your own "Vertical Sensitivity Multiplier" Setting.
